# Generated by Django 5.1.4 on 2025-07-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "นักเรียน"),
                    ("teacher", "อาจารย์"),
                    ("manager", "อาจารย์ประจำวิชา"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
