# Generated by Django 5.1.4 on 2025-03-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="role",
            field=models.IntegerField(default=1),
        ),
    ]
