# Generated by Django 5.1.4 on 2025-07-31 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_member_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="teacher",
        ),
        migrations.AddField(
            model_name="news",
            name="created_by",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
