# Generated by Django 5.1.4 on 2025-03-02 22:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_member_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="availabletime",
            old_name="time",
            new_name="end_time",
        ),
        migrations.AddField(
            model_name="appointment",
            name="students",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="availabletime",
            name="start_time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="score",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to="myapp.project",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
