# Generated by Django 5.1.4 on 2025-07-31 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_remove_news_teacher_news_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="score",
            name="teacher",
        ),
        migrations.AddField(
            model_name="score",
            name="evaluator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_scores",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_scores",
                to="myapp.student",
            ),
        ),
    ]
