# Generated by Django 5.1.4 on 2025-07-31 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_remove_score_teacher_score_evaluator_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="score",
            name="evaluator",
        ),
        migrations.AddField(
            model_name="score",
            name="teacher",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.teacher",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="score",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.student"
            ),
        ),
    ]
