# Generated by Django 5.1.4 on 2025-03-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_appointment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
