# Generated by Django 5.1.4 on 2025-03-06 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_news_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="member_ptr",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="teacher",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
