# Generated by Django 5.1.4 on 2025-08-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_remove_score_evaluator_score_teacher_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B+", "B+"),
                    ("B", "B"),
                    ("C+", "C+"),
                    ("C", "C"),
                    ("D+", "D+"),
                    ("D", "D"),
                    ("F", "F"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
