# Generated by Django 5.1.4 on 2025-03-07 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_alter_teacher_member_ptr"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.manager",
            ),
        ),
    ]
