# Generated by Django 5.1.4 on 2025-03-07 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_news_manager"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="manager",
        ),
    ]
