# Generated by Django 5.1.4 on 2025-03-08 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_remove_news_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="member_ptr",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="student",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
