# Generated by Django 5.1.4 on 2025-03-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_alter_student_member_ptr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="file_type",
        ),
        migrations.AddField(
            model_name="file",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/files/"),
        ),
    ]
