# Generated by Django 5.1.4 on 2025-03-10 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_remove_file_file_type_file_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="availabletime",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
