# Generated by Django 5.1.4 on 2025-03-11 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_availabletime_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.student",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="score",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.teacher",
            ),
            preserve_default=False,
        ),
    ]
