# Generated by Django 5.1.4 on 2025-03-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_score_student_score_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="meeting_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
