# Generated by Django 5.1.4 on 2025-03-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0013_appointment_meeting_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
