# Generated by Django 5.1.4 on 2025-03-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0014_alter_appointment_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
