# Generated by Django 5.1.4 on 2025-03-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0015_alter_file_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="students",
            field=models.ManyToManyField(related_name="projects", to="myapp.student"),
        ),
    ]
