# Generated by Django 5.1.4 on 2025-03-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0016_alter_project_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="teachers",
            field=models.ManyToManyField(
                blank=True, related_name="teacher_appointments", to="myapp.teacher"
            ),
        ),
    ]
