# Generated by Django 5.1.4 on 2025-03-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0017_appointment_teachers"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
