# Generated by Django 5.1.4 on 2025-03-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0018_appointment_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="accepted_teachers",
            field=models.TextField(blank=True, null=True),
        ),
    ]
